analyzer:
  # Lint rules and documentation, see http://dart-lang.github.io/linter/lints
  exclude:
    - lib/sampleCode.dart
    - test/sampleCode.dart
    - test/**
    - test/*.*
  language:
    enableSuperMixins: true

linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - avoid_returning_null          # Avoid returning null from members whose return type is bool, double, int, or num.
    - prefer_conditional_assignment # Prefer using ??= over testing for null.
    - no_adjacent_strings_in_list
    - avoid_null_checks_in_equality_operators # As null is a special type, no class can be equivalent to it. Use "is" "type" instead.